logo: Jim's Studio Site # add logo name
title: Jim's Studio Site
description: > # this means to ignore newlines until "baseurl:"
  My studio Site profiling all the work I will be doing in the Boulder Digital Works (Strategic Communcation Design)
  at University of Colorado-Boulder.
permalink: ':title/'
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://jimmurphy.studio" # the base hostname & protocol for your site, e.g. http://example.com

# Banner settings
video: mountains.mp4 # add banner video. Add your video file to the folder video
banner-title: Jim's Studio Site # add banner title
banner-desc: “Write it. Shoot it. Publish it. Crochet it, sauté it, whatever. MAKE.”
 ― Joss Whedon # add banner description

# Author settings
author-pic: Headshot.jpg # your photo
author-name: Jim Murphy # your name
about-author: Michigan born and raised. Colorado for grad school at CU-Boulder. # about author
email: jamu6792@colorado.edu # your email
phone:  # your pnone number
website: https://jimmurphy.studio # you website

# Social link
google_url:    # add url link
twitter_url: https://twitter.com/wasgunnabut # add url link
instagram_url: https://www.instagram.com/wasgunnabut/ # add url link
pinterest_url: # add url link
dribbble_url:  # add url link
facebook_url: https://www.facebook.com/wasgunnabut # add url link

# Disqus
discus_identifier: mr-murphy # add your discus identifier

# Newsletter
mailchimp: # add your MailChimp form identifier. For example - blogenjoyfreedom.us16.list-manage.com/subscribe/post?u=cd56155d76ddeeb4c0bc4d080&amp;id=7a526cd13e

# Tracker
analytics:

# Paginate
paginate: 12
paginate_path: /page:num/

# Build settings
markdown: kramdown
plugins:
  - jekyll-paginate
  - jekyll-sitemap

include: [_pages]
exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
